version: '3.7'

services:

  main:
    image: castor/php-dev
    build:
      context: .
      dockerfile: main/Dockerfile
    volumes:
      - ../../:/castor/lib
    working_dir: /castor/lib
    user: castor
